import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { ThemeProvider } from "@/components/providers/ThemeProvider";
import { cookies } from "next/headers";
import { LogIn } from "lucide-react";
import Login from "@/components/Login";
import { Separator } from "@radix-ui/react-dropdown-menu";
import { Toaster } from "@/components/ui/sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const auth = cookieStore.get("refresh");
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {auth && (
            <main className="w-full">
              <Navbar />
              <Separator className="w-[1px]"/>
              <div className="px-4">{children}</div>
              <Toaster position="bottom-right" expand={true} />
            </main>
          )}
          {!auth && <Login />}
        </ThemeProvider>
      </body>
    </html>
  );
}
