repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-docstring-first
      - id: check-json
      - id: check-merge-conflict
      - id: check-yaml
      - id: debug-statements
      - id: trailing-whitespace

  - repo: https://github.com/PyCQA/autoflake
    rev: v2.2.1
    hooks:
      - id: autoflake
        args: [ '--in-place','--remove-unused-variable', '--remove-all-unused-imports' ]

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        exclude: ^.*\b(migrations)\b.*$

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.10.1
    hooks:
      - id: pyupgrade
        args: [ '--py37-plus', '--keep-runtime-typing' ]

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort

  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        additional_dependencies: [
          flake8-2020,
          #          flake8-bandit,
          #          flake8-blind-except,
          flake8-breakpoint,
          flake8-broken-line,
          #          flake8-bugbear,
          flake8-builtins,
          flake8-commas,
          flake8-debugger,
          flake8-eradicate,
          #          flake8-fixme,
          #          flake8-logging-format,
          #          flake8-pep3101,
          #          flake8-print,
          #          flake8-pytest,
          #          flake8-pytest-style,
          #          flake8-raise,
          flake8-django,
          flake8-comprehensions,
          flake8-builtins,
          #          flake8-docstrings
          #          flake8_simplify
          #          pep8-naming
        ]
