# Generated by Django 5.2.6 on 2025-09-26 22:52

import django.db.models.deletion
import drf_chunked_upload.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('file', models.FileField(editable=False, upload_to='uploads/scan', verbose_name='Файл')),
                ('status', models.CharField(choices=[('preparing_for_viewing', 'Подготовка к просмотру:#3F391A:#EEE6BE'), ('ready_to_watch', 'Готов к просмотру:#0078E7:#BED7EE'), ('ai_processing_completed', 'Завершена обработка ИИ:#057306:#D7FCD7'), ('in_processing', 'В обработке ИИ:#381BEB:#ECE9FD'), ('viewed', 'Просмотрен:#6D06C6:#F3E8FF'), ('adjusted_by_user', 'Скорректирован пользователем:#8B7500:#FEF8C3')], default='preparing_for_viewing', max_length=50, verbose_name='Статус')),
                ('markup_file', models.FileField(blank=True, editable=False, null=True, upload_to='uploads/markup', verbose_name='Файл разметки')),
                ('work_ai_status', models.CharField(choices=[('in_work', 'В работе'), ('in_processing', 'В обработке'), ('worked_out', 'Работа закончена')], default='in_work', max_length=50, verbose_name='Статус работы ИИ')),
                ('study_uid', models.CharField(max_length=255, verbose_name='Уникальный идентификатор исследования')),
                ('series_uid', models.CharField(max_length=255, verbose_name='Уникальный идентификатор серии')),
                ('path_to_study', models.CharField(blank=True, max_length=255, null=True, verbose_name='Путь к исследованию')),
                ('probability_of_pathology', models.FloatField(blank=True, null=True, verbose_name='Вероятность патологии')),
                ('pathology', models.IntegerField(blank=True, null=True, verbose_name='Норма ли патология')),
                ('processing_status', models.CharField(blank=True, choices=[('Success', 'Успешно'), ('Failure', 'Ошибка')], max_length=50, null=True, verbose_name='Статус обработки')),
                ('time_of_processing', models.FloatField(blank=True, null=True, verbose_name='Время обработки (секунды)')),
            ],
            options={
                'verbose_name': 'Скан',
                'verbose_name_plural': 'Сканы',
            },
        ),
        migrations.CreateModel(
            name='ScanUploadChunked',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(max_length=255, null=True, upload_to=drf_chunked_upload.models.generate_filename)),
                ('filename', models.CharField(max_length=255)),
                ('offset', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Incomplete'), (2, 'Complete')], default=1)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('scan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='chunked_upload', to='patient.scan', verbose_name='Скан')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Чанк',
                'verbose_name_plural': 'Чанки',
            },
        ),
    ]
