# Generated by Django 5.2.6 on 2025-09-28 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='file',
            field=models.FileField(upload_to='uploads/scan', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='markup_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/markup', verbose_name='Файл разметки'),
        ),
    ]
