# Generated by Django 5.2.6 on 2025-09-30 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_alter_scan_file_alter_scan_markup_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/scan', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='series_uid',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Уникальный идентификатор серии'),
        ),
        migrations.AlterField(
            model_name='scan',
            name='study_uid',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Уникальный идентификатор исследования'),
        ),
    ]
