# Generated by Django 5.2.6 on 2025-09-30 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_alter_scan_file_alter_scan_series_uid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DicomInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='Название файла')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dicom_info', to='patient.scan', verbose_name='Скан')),
            ],
            options={
                'verbose_name': 'Диком информация',
                'verbose_name_plural': 'Диком информация',
            },
        ),
        migrations.CreateModel(
            name='Slice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slice_number', models.IntegerField(verbose_name='Номер среза')),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/slices/', verbose_name='Фото среза')),
                ('probability', models.FloatField(blank=True, null=True, verbose_name='Вероятность')),
                ('dicom_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slices', to='patient.dicominfo', verbose_name='Информация Dicom')),
            ],
            options={
                'verbose_name': 'Срез',
                'verbose_name_plural': 'Срезы',
                'ordering': ['slice_number'],
            },
        ),
    ]
