# Generated by Django 5.2.6 on 2025-10-02 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_dicominfo_slice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scan',
            name='status',
        ),
    ]
