# Generated by Django 5.2.6 on 2025-10-02 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_remove_scan_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scan',
            name='file',
        ),
        migrations.AlterField(
            model_name='scan',
            name='path_to_study',
            field=models.FileField(blank=True, null=True, upload_to='uploads/scan', verbose_name='Путь к исследованию'),
        ),
    ]
